export const stateOptions = [
    { value: 'Andaman and Nicobar Islands', label: 'Andaman and Nicobar Islands' },
    { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
    { value: 'Arunachal Pradesh', label: 'Arunachal Pradesh' },
    { value: 'Assam', label: 'Assam' },
    { value: 'Bihar', label: 'Bihar' },
    { value: 'Chandigarh', label: 'Chandigarh' },
    { value: 'Chhattisgarh', label: 'Chhattisgarh' },
    { value: 'Dadra and Nagar Haveli', label: 'Dadra and Nagar Haveli' },
    { value: 'Daman and Diu', label: 'Daman and Diu' },
    { value: 'Delhi', label: 'Delhi' },
    { value: 'Goa', label: 'Goa' },
    { value: 'Gujarat', label: 'Gujarat' },
    { value: 'Haryana', label: 'Haryana' },
    { value: 'Himachal Pradesh', label: 'Himachal Pradesh' },
    { value: 'Jammu and Kashmir', label: 'Jammu and Kashmir' },
    { value: 'Jharkhand', label: 'Jharkhand' },
    { value: 'Karnataka', label: 'Karnataka' },
    { value: 'Kerala', label: 'Kerala' },
    { value: 'Ladakh', label: 'Ladakh' },
    { value: 'Lakshadweep', label: 'Lakshadweep' },
    { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
    { value: 'Maharashtra', label: 'Maharashtra' },
    { value: 'Manipur', label: 'Manipur' },
    { value: 'Meghalaya', label: 'Meghalaya' },
    { value: 'Mizoram', label: 'Mizoram' },
    { value: 'Nagaland', label: 'Nagaland' },
    { value: 'Odisha', label: 'Odisha' },
    { value: 'Puducherry', label: 'Puducherry' },
    { value: 'Punjab', label: 'Punjab' },
    { value: 'Rajasthan', label: 'Rajasthan' },
    { value: 'Sikkim', label: 'Sikkim' },
    { value: 'Tamil Nadu', label: 'Tamil Nadu' },
    { value: 'Telangana', label: 'Telangana' },
    { value: 'Tripura', label: 'Tripura' },
    { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
    { value: 'Uttarakhand', label: 'Uttarakhand' },
    { value: 'West Bengal', label: 'West Bengal' },
];

export const cityOptions = [
    { value: 'Agra', label: 'Agra' },
    { value: 'Ahmedabad', label: 'Ahmedabad' },
    { value: 'Alappuzha', label: 'Alappuzha' },
    { value: 'Alwar', label: 'Alwar' },
    { value: 'Amritsar', label: 'Amritsar' },
    { value: 'Aurangabad', label: 'Aurangabad' },
    { value: 'Bangalore', label: 'Bangalore' },
    { value: 'Bharatpur', label: 'Bharatpur' },
    { value: 'Bhavnagar', label: 'Bhavnagar' },
    { value: 'Bhikaner', label: 'Bhikaner' },
    { value: 'Bhopal', label: 'Bhopal' },
    { value: 'Bhubaneshwar', label: 'Bhubaneshwar' },
    { value: 'Bodh Gaya', label: 'Bodh Gaya' },
    { value: 'Calangute', label: 'Calangute' },
    { value: 'Chandigarh', label: 'Chandigarh' },
    { value: 'Chennai', label: 'Chennai' },
    { value: 'Chittaurgarh', label: 'Chittaurgarh' },
    { value: 'Coimbatore', label: 'Coimbatore' },
    { value: 'Cuttack', label: 'Cuttack' },
    { value: 'Dalhousie', label: 'Dalhousie' },
    { value: 'Dehradun', label: 'Dehradun' },
    { value: 'Delhi', label: 'Delhi' },
    { value: 'Diu-Island', label: 'Diu-Island' },
    { value: 'Ernakulam', label: 'Ernakulam' },
    { value: 'Faridabad', label: 'Faridabad' },
    { value: 'Gaya', label: 'Gaya' },
    { value: 'Gangtok', label: 'Gangtok' },
    { value: 'Ghaziabad', label: 'Ghaziabad' },
    { value: 'Gurgaon', label: 'Gurgaon' },
    { value: 'Guwahati', label: 'Guwahati' },
    { value: 'Gwalior', label: 'Gwalior' },
    { value: 'Haridwar', label: 'Haridwar' },
    { value: 'Hyderabad', label: 'Hyderabad' },
    { value: 'Imphal', label: 'Imphal' },
    { value: 'Indore', label: 'Indore' },
    { value: 'Jabalpur', label: 'Jabalpur' },
    { value: 'Jaipur', label: 'Jaipur' },
    { value: 'Jaisalmer', label: 'Jaisalmer' },
    { value: 'Jalandhar', label: 'Jalandhar' },
    { value: 'Jamshedpur', label: 'Jamshedpur' },
    { value: 'Jodhpur', label: 'Jodhpur' },
    { value: 'Junagadh', label: 'Junagadh' },
    { value: 'Kanpur', label: 'Kanpur' },
    { value: 'Kanyakumari', label: 'Kanyakumari' },
    { value: 'Khajuraho', label: 'Khajuraho' },
    { value: 'Khandala', label: 'Khandala' },
    { value: 'Kochi', label: 'Kochi' },
    { value: 'Kodaikanal', label: 'Kodaikanal' },
    { value: 'Kolkata', label: 'Kolkata' },
    { value: 'Kota', label: 'Kota' },
    { value: 'Kottayam', label: 'Kottayam' },
    { value: 'Kovalam', label: 'Kovalam' },
    { value: 'Lucknow', label: 'Lucknow' },
    { value: 'Ludhiana', label: 'Ludhiana' },
    { value: 'Madurai', label: 'Madurai' },
    { value: 'Manali', label: 'Manali' },
    { value: 'Mangalore', label: 'Mangalore' },
    { value: 'Margao', label: 'Margao' },
    { value: 'Mathura', label: 'Mathura' },
    { value: 'Mountabu', label: 'Mountabu' },
    { value: 'Mumbai', label: 'Mumbai' },
    { value: 'Mussoorie', label: 'Mussoorie' },
    { value: 'Mysore', label: 'Mysore' },
    { value: 'Manali', label: 'Manali' },
    { value: 'Nagpur', label: 'Nagpur' },
    { value: 'Nainital', label: 'Nainital' },
    { value: 'Noida', label: 'Noida' },
    { value: 'Ooty', label: 'Ooty' },
    { value: 'Orchha', label: 'Orchha' },
    { value: 'Panaji', label: 'Panaji' },
    { value: 'Patna', label: 'Patna' },
    { value: 'Pondicherry', label: 'Pondicherry' },
    { value: 'Porbandar', label: 'Porbandar' },
    { value: 'Portblair', label: 'Portblair' },
    { value: 'Pune', label: 'Pune' },
    { value: 'Puri', label: 'Puri' },
    { value: 'Pushkar', label: 'Pushkar' },
    { value: 'Rajkot', label: 'Rajkot' },
    { value: 'Rameswaram', label: 'Rameswaram' },
    { value: 'Ranchi', label: 'Ranchi' },
    { value: 'Sanchi', label: 'Sanchi' },
    { value: 'Secunderabad', label: 'Secunderabad' },
    { value: 'Shimla', label: 'Shimla' },
    { value: 'Surat', label: 'Surat' },
    { value: 'Thanjavur', label: 'Thanjavur' },
    { value: 'Thiruchchirapalli', label: 'Thiruchchirapalli' },
    { value: 'Thrissur', label: 'Thrissur' },
    { value: 'Tirumala', label: 'Tirumala' },
    { value: 'Udaipur', label: 'Udaipur' },
    { value: 'Vadodra', label: 'Vadodra' },
    { value: 'Varanasi', label: 'Varanasi' },
    { value: 'Vasco-Da-Gama', label: 'Vasco-Da-Gama' },
    { value: 'Vijayawada', label: 'Vijayawada' },
    { value: 'Visakhapatnam', label: 'Visakhapatnam' }
];

export const genderOptions = [
    { value: 'Male', label: 'Male' },
    { value: 'Female', label: 'Female' },
    { value: 'Others', label: 'Others' }
];